NewsAggregationApplication.UI/Controllers/ArticleController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsAggregationApplication.UI.Interfaces;
using NewsAggregationApplication.UI.Mappers;

namespace NewsAggregationApplication.UI.Controllers;

public class ArticleController : Controller
{
    private readonly IArticleService _articleService;
    private readonly ICommentService _commentService;
    private readonly ArticleMapper _articleMapper;
    private readonly CommentMapper _commentMapper;
    private readonly ILogger<ArticleController> _logger;

    public ArticleController(IArticleService articleService, ICommentService commentService, ArticleMapper articleMapper, CommentMapper commentMapper, ILogger<ArticleController> logger)
    {
        _articleService = articleService;
        _commentService = commentService;
        _articleMapper = articleMapper;
        _commentMapper = commentMapper;
        _logger = logger;
    }

    
    public async Task<IActionResult> Index()
    {
        ViewData["IsAdmin"] = User.IsInRole("Admin");
        Guid userId = User.Identity.IsAuthenticated ? Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) : Guid.Empty;
        var articles = await _articleService.GetArticlesAsync(userId);
        var model = articles.Select(a => _articleMapper.ArticleDtoToArticleModel(a)).ToList();
        return View(model);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Aggregate()
    {
        try
        {
            await _articleService.AggregateFromSourceAsync(CancellationToken.None);
            TempData["SuccessMessage"] = "RSS feeds successfully aggregated.";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to aggregate RSS feeds.");
            TempData["ErrorMessage"] = "Failed to aggregate RSS feeds. Check logs for details.";
            return RedirectToAction("Index");
        }
       
        
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> DeleteArticle(Guid id)
    {
        try
        {
            var deleted = await _articleService.DeleteArticleAsync(id);
            if (!deleted)
            {
                _logger.LogWarning($"Article with ID: {id} not found.");
                TempData["ErrorMessage"] = $"Article with ID: {id} not found.";
                return RedirectToAction(nameof(Index));
            }
            _logger.LogInformation($"Article with ID: {id} deleted successfully.");
            return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error deleting article with ID: {id}.");
            TempData["ErrorMessage"] = "An error occurred while deleting the article.";
            return RedirectToAction(nameof(Index));

        }
    }
    public async Task<IActionResult> Details(Guid id)
    {
        try
        {
            Guid userId = User.Identity.IsAuthenticated ? Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) : Guid.Empty;

            var articleDto = await _articleService.GetArticlesByIdAsync(id,userId);
            if (articleDto == null)
            {
                _logger.LogWarning($"Article with ID: {id} not found.");
               TempData["ErrorMessage"] = $"Article with ID: {id} not found.";
               return RedirectToAction(nameof(Index));

            }

            var article = _articleMapper.ArticleDtoToArticleModel(articleDto);
            var comments = await _commentService.GetCommentsByArticleIdAsync(id);
            article.Comments = comments.Select(_commentMapper.CommentDtoToCommentModel).ToList();

            return View(article);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Failed to retrieve details for article with ID: {id}.");
            TempData["ErrorMessage"] = "An error occurred while retrieving the article details.";
            return RedirectToAction(nameof(Index));
        }
    }
    
    [Authorize]
    public async Task<IActionResult> SortByPositivity(bool sortByPositive)
    {
        ViewData["IsAdmin"] = User.IsInRole("Admin");
        Guid userId = User.Identity.IsAuthenticated ? Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) : Guid.Empty;
        var articles = await _articleService.GetSortedArticlesByPositivityAsync(userId, sortByPositive);
        var model = articles.Select(a => _articleMapper.ArticleDtoToArticleModel(a)).ToList();
        return View("Index", model);
    }

    [Authorize]
    public async Task<IActionResult> SortByDate(bool sortByNewest)
    {
        ViewData["IsAdmin"] = User.IsInRole("Admin");
        Guid userId = User.Identity.IsAuthenticated
            ? Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))
            : Guid.Empty;
        var articles = await _articleService.GetSortedArticlesByDate(userId, sortByNewest);
        var model = articles.Select(a => _articleMapper.ArticleDtoToArticleModel(a)).ToList();
        return View("Index", model);
    }
   

    
}

NewsAggregationApplication.UI/Controllers/BookmarkController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsAggregationApplication.UI.DTOs;
using NewsAggregationApplication.UI.Interfaces;
using NewsAggregationApplication.UI.Mappers;
using NewsAggregationApplication.UI.Models;
using NewsAggregationApplication.UI.Services;

namespace NewsAggregationApplication.UI.Controllers;

public class BookmarkController : Controller
{
    private readonly IBookmarkService _bookmarkService;
    private readonly ILogger<BookmarkService> _logger;
    private readonly BookmarkMapper _bookmarkMapper;
    private readonly ArticleMapper _articleMapper;
    

    public BookmarkController(IBookmarkService bookmarkService, ILogger<BookmarkService> logger, BookmarkMapper bookmarkMapper, ArticleMapper articleMapper)
    {
        _bookmarkService = bookmarkService;
        _logger = logger;
        _bookmarkMapper = bookmarkMapper;
        _articleMapper = articleMapper;
    }
    
    [Authorize]
    public async Task<IActionResult> Index()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrEmpty(userId))
        {
            _logger.LogError("User ID is null in Index method of BookmarkController.");
            return Unauthorized();
        }

        try
        {
            var articleDtos = await _bookmarkService.GetBookmarkArticlesAsync(Guid.Parse(userId));
            var articleModels = articleDtos.Select(adto => _articleMapper.ArticleDtoToArticleModel(adto)).ToList();
            return View(articleModels);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to fetch bookmarked articles.");
            TempData["ErrorMessage"] = "Failed to fetch bookmarked articles.";
            return View(new List<ArticleModel>()); // Return an empty view in case of failure
        }
    }

    
   
    [Authorize]
    [HttpPost]
    public async Task<IActionResult> ToggleBookmark(Guid articleId, string returnUrl)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrEmpty(userId))
        {
            return Unauthorized();
        }

        try
        {
            var isBookmarked = await _bookmarkService.IsArticleBookmarkedByUser(articleId, Guid.Parse(userId));
            if (isBookmarked)
            {
                await _bookmarkService.RemoveBookmarkAsync(articleId, Guid.Parse(userId));
                _logger.LogInformation($"Bookmark removed for article {articleId}.");
                TempData["SuccessMessage"] = "Bookmark removed successfully.";

            }
            else
            {
                var bookmarkDto = new BookmarkDto
                {
                    Id = Guid.NewGuid(),
                    UserId = Guid.Parse(userId),
                    ArticleId = articleId,
                    IsBookmarked = isBookmarked
                };
                await _bookmarkService.BookmarkArticleAsync(bookmarkDto);
                _logger.LogInformation($"Article {articleId} bookmarked.");
               

            }

            return Redirect(returnUrl);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error toggling bookmark for article {articleId}.");
            TempData["ErrorMessage"] = "An error occurred while toggling the bookmark.";
            return Redirect(returnUrl);
        }
    }

   
}

NewsAggregationApplication.UI/Controllers/CommentController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NewsAggregationApplication.Data.Entities;
using NewsAggregationApplication.UI.DTOs;
using NewsAggregationApplication.UI.Interfaces;
using NewsAggregationApplication.UI.Mappers;
using NewsAggregationApplication.UI.Models;

namespace NewsAggregationApplication.UI.Controllers;


public class CommentController : Controller
{

    private readonly ICommentService _commentService;
    private readonly UserManager<User> _userManager;
    private readonly ILogger<CommentController> _logger;
    private readonly CommentMapper _commentMapper;

    public CommentController(ICommentService commentService, UserManager<User> userManager, ILogger<CommentController> logger, CommentMapper commentMapper)
    {
        _commentService = commentService;
        _userManager = userManager;
        _logger = logger;
        _commentMapper = commentMapper;
    }


    
    [HttpPost]
    public async Task<IActionResult> AddComment(Guid articleId, CommentViewModel model)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrEmpty(userId))
        {
            TempData["ErrorMessage"] = "User is not authorized.";
            return Unauthorized();
        }

        try
        {
            var commentDto = _commentMapper.CommentModelToCommentDto(model);
            commentDto.ArticleId = articleId;
            commentDto.UserId = Guid.Parse(userId);
            commentDto.CreatedAt = DateTime.UtcNow;

            
            var result = await _commentService.AddCommentAsync(commentDto);
            if (result)
            {
                _logger.LogInformation("Comment added.");
                return RedirectToAction("Details", "Article", new { id = articleId });
            }
            TempData["ErrorMessage"] = "Unable to add comment.";
            return RedirectToAction("Details", "Article", new { id = articleId });
            
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to add comment.");
            TempData["ErrorMessage"] = "An error occurred while adding the comment.";
            return RedirectToAction("Details", "Article", new { id = articleId, error = "Failed to add comment" });
        }

        
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> EditComment(Guid articleId, EditCommentViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["Error"] = "There was a problem with your submission.";
            return RedirectToAction("Details","Article,new {id = articleId}");
        }
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        var commentDto = _commentMapper.EditCommentViewModelToCommentDto(model);
        commentDto.UserId = Guid.Parse(userId);

        var success = await _commentService.EditCommentAsync(commentDto);

        if (success)
        {
            _logger.LogInformation("Comment edited successfully.");
            TempData["SuccessMessage"] = "Comment could not be edited.";
            return RedirectToAction("Details", "Article", new { id = articleId });
        }

        _logger.LogWarning("Failed to edit comment.");
        TempData["ErrorMessage"] = "Comment could not be edited.";
        return RedirectToAction("Details", "Article", new { id = articleId });
        
    }

   
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> DeleteComment(Guid articleId, Guid commentId)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        bool isAdmin = User.IsInRole("Admin");

        try
        {
            var success = await _commentService.DeleteCommentAsync(commentId);
            if (success)
            {
                _logger.LogInformation("Comment successfully deleted.");
            }
            else
            {
                _logger.LogWarning("Failed to delete comment.");
                TempData["Error"] = "Comment could not be deleted.";
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting comment.");
            TempData["Error"] = "An error occurred while deleting the comment.";
        }

        return RedirectToAction("Details", "Article", new { id = articleId });
    }
}
    

NewsAggregationApplication.UI/Views/Shared/_AddComment.cshtml
@model CommentViewModel

<form asp-action="AddComment" asp-controller="Comment" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" name="articleId" value="@Model.ArticleId" />
    <div class="form-group">
        <label for="content">Add a Comment</label>
        <textarea id="content" name="content" class="form-control"></textarea>
        

    </div>
    <button type="submit" class="btn btn-primary">Post Comment</button>
</form>

NewsAggregationApplication.UI/Views/Shared/_DeleteComment.cshtml
@model CommentViewModel

<form asp-action="DeleteComment" asp-controller="Comment" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" name="articleId" value="@Model.ArticleId" />
    <input type="hidden" name="commentId" value="@Model.Id" />
    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
</form>

NewsAggregationApplication.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using NewsAggregationApplication.Data.Entities
@inject SignInManager<User> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - NewsWise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/NewsAggregationApplication.UI.styles.css" asp-append-version="true"/>
  
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Article" asp-action="Index">NewsWise</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                        </li>
                        
                    </ul>
                    <ul class="nav justify-content-center">
                        @if (SignInManager.IsSignedIn(User))
                        {
                           
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmark" asp-action="Index">Bookmarks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="ChangePassword">Settings</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                            
                            
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - NewsWise - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NewsAggregationApplication.UI/Views/Shared/_LikeButton.cshtml
@model LikeModel

<form asp-action="Like" asp-controller="Like"method="post">
    <input type="hidden" asp-for="ArticleId"/>
    <button type="submit" class="btn btn-primary">Like</button>
</form>

NewsAggregationApplication.UI/Views/Shared/_UnlikeButton.cshtml
@model LikeModel

<form asp-action="Unlike" asp-controller="Like" method="post">
    <input type="hidden" asp-for="ArticleId"/>
    <button type="submit" class="btn btn-warning">Unlike</button>
</form>